---
  - name: "Install & Configure Maria DB"
    hosts: db
    become: yes
    tasks:
      - name: add Mariadb repo
        copy:
          src: mariadb.repo
          dest: /etc/yum.repos.d/mariadb.repo
      - name: "Install Maria DB"
        package:
          name:
           - MariaDB-server
           - python3-PyMySQL
          state: present
      - name: "Start Maria DB"
        service:
          name: mariadb
          state: started
          enabled: true
      - name: Provide access to the database
        mysql_user:
          name: "root"
          password: "testjava"
          host: localhost
          login_user: "root"
          login_password: "testjava"
          check_implicit_admin: yes
          priv: "*.*:ALL,GRANT"
          state: present

      - name: "Check script file flag status"
        stat:
          path: "db_script_flag"
        register: flag_file_status

      - name: "Run sample data script"
        mysql_db:
          name: "testdb"
          state: present
          login_user: "testjava"
          login_password: "testjava"
          login_unix_socket: /var/lib/mysql/mysql.sock
      - name: insert adat in to DB
        mysql_db:
          name: "testdb"
          state: import
          target: "/tmp/db_script.sql"
          login_user: "testjava"
          login_password: "testjava"
        when: flag_file_status.stat.exists == false

      - name: "Create flag file"
        copy:
          content: "flag file content"
          dest: "db_script_flag"
        when: flag_file_status.stat.exists == false
