---
  - name: "Install & Configure Maria DB"
    hosts: db
    become: yes
    vars:
      mysql_root_password: password
    tasks:
      - name: "Install Maria DB"
        yum:
          name:
           - mariadb
           - mariadb-server
          state: present
      - name: "Start Maria DB"
        systemd:
          name: mariadb
          state: started
          enabled: yes
      - name: Remove the test database
        database:  
          name: test
          login_user: root
          login_unix_socket: "/var/lib/mysql/mysql.sock"
          state: absent
      - name: "Create database"
        mysql_db:
          name: "test-1"
